### PR TITLE
Anchor iou thresh

### PR DESCRIPTION
**Pull request by gan3sh500**
The change we had discussed. Please see changes. It seems to be the correct logic to me. I think it might cause issue of ignoring some bbox if multiple gt bboxes are centred in same grid position.

### CODE REVIEW

**Comment by david8862** [comment]
Awesome fix! I also notice that in YOLOv4 ablation studies, separately using the IT feature may have negative impact of detection mAP.
IoU_thresh

So I may add a CLI option to control it. Anyway many thanks for your great contribution to this repo!

**Comment by david8862** [comment]
Regarding to load COCO pretrained weights for initialization, you can use "--weights_path" option for a COCO .h5 and uncomment [skip_mismatch](https://github.com/david8862/keras-YOLOv3-model-set/blob/master/yolo3/model.py#L213) to avoid loading error (I comment it out because this option is uncompatible with old TF version). Generally it should work same as darknet or pytorch revision.

**Comment by gan3sh500** [comment]
For COCO h5 do you mean yolov4.h5 you use for inference? I tried to load that but many layers had mismatch. And training was not any faster. I think loading is not proper. I was thinking of training COCO on my machine and getting a checkpoint manually to compare. Mismatch should only be the 3 yolo head layers right?

**Comment by david8862** [comment]
@gan3sh500 yes for the .h5 file and mismatch point, so `model_body.load_weights(weights_path, skip_mismatch=True)` should be able to solve the loading problem. If you want to reproduce the COCO result from scratch, as I know the standard way is training CSPDarknet53 backbone on Imagenet first, and then transfer to COCO. In current implementation I tried to use the backbone weights converted from "csdarknet53-omega_final.weights" to initialize, but from validation result it's not trained on Imagenet.

**Pull request merged**
